### ISSUE TITLE
Imagens do Quadro (api google drive/dropbox)

### ISSUE THREAD

**Issue by cleversonahum** [SmartClass-UFPA/server#11]
A API deve fazer uma requisição para o Google Drive ou para o DropBox para realizar o upload das imagens, O download das mesmas e a listagem de acordo com a matéria ou data

**Comment by brunoricardojava** [comment]
Esses serviços já possuem essas APIs, "https://dropbox.github.io/dropbox-api-v2-explorer/#files_download".

**Comment by cleversonahum** [comment]
Eu pensei em fazer as nossas com as bibliotecas deles que nem pensei nessa possibilidade que é muito melhor mesmo, vlw @brunoricardojava

**Comment by cleversonahum** [comment]
Decidimos que vamos utilizar a própria API do Dropbox, já pesquisei e deixei o código pronto com requisições usando o curl do linux funcionando e enviei para a @lidiaxp . Já não vamos precisar ter nada no nosso servidor já que vamos usar o do próprio dropbox.
