### ISSUE TITLE
Criar rede docker entre BD e API

### ISSUE THREAD

**Issue by cleversonahum** [SmartClass-UFPA/server#14]
Criar uma rede docker para os containers para não precisar ficar alterando o IP dos containers toda hora

**Comment by brunoricardojava** [comment]
Como assim? Não da pra usar link entre os containers?

**Comment by cleversonahum** [comment]
Dá sim @brunoricardojava só que é uma função em desuso, melhor criar uma rede entre eles, mas to fazendo aqui um docker-composer que já vai levantar o servidor e o banco de dados juntos logo
